version: '3.7'

services:

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    volumes:
      - ./config/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/dev/nginx/cache:/data/nginx/cache
      - ./cert:/etc/cert
      - ./ancean-back/ancean/static:/app/usr/static
      - ./ancean-back/ancean/media:/app/usr/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web
    networks:
      - default-bridge

  api:
    build:  
      context: ./ancean-back
      dockerfile: Dockerfile.prod
    container_name: api-local
    volumes:
      - ./ancean-back/ancean/media:/usr/app/ancean/media
    secrets:
      - source: postgres-secrets
        target: /usr/app/ancean/secrets/postgres-secrets.json
      - source: django-secrets
        target: /usr/app/ancean/secrets/django-secrets.json
      - source: oauth-connection
        target: /usr/app/ancean/secrets/oauth-secrets.json
    ports:
      - "5050:8000"
    networks:
      - default-bridge

  web:
    build:
      context: ./ancean-front
      dockerfile: Dockerfile.local
    container_name: web-local
    volumes:
      - /usr/app/node_modules
      - ./ancean-front:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - EXECUTION_ENV=local
    depends_on:
      - api
    ports:
      - "3030:3000"
    networks:
      - default-bridge

  postgres:
    image: postgres:14
    restart: always
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ancean
      POSTGRES_PASSWORD: g=@#tlb074vn5av(3=(bp%lnmx1077y@oe2*pd3f729n4%5
    volumes:
      - ./config/dev/data:/var/lib/postgresql/data
    networks:
      - default-bridge

secrets:
  postgres-secrets:
    file: ./secrets/postgres-secrets.json
  django-secrets:
    file: ./secrets/django-secrets.json
  oauth-connection:
    file: ./secrets/oauth-secrets.json

networks:
  default-bridge:
    name: dev-net