services:

  api:
    build:  
      context: ./ancean-back
      dockerfile: Dockerfile.local
    container_name: api-local
    volumes:
      - ./ancean-back:/usr/app
    secrets:
      - source: django-connection
        target: /usr/app/ancean/secrets/django-secrets.json
    ports:
      - 8000:8000
    networks:
      - ancean-local-net

  web:
    build:
      context: ./ancean-front
      dockerfile: Dockerfile.local
    container_name: web-local
    volumes:
      - /usr/app/node_modules
      - ./ancean-front:/usr/app
    environment:
      CHOKIDAR_USEPOLLING: true
      EXECUTION_ENV: local
    ports:
      - 3000:3000
    networks:
      - ancean-local-net

  jenkins-master:
    build:
      context: ./jenkins
    container_name: jenkins-master
    volumes:
      - $PWD/jenkins/jenkins_home:/var/jenkins_home
      - $PWD/jenkins/pipeline:/var/jenkins_home/my_pipeline
      - $PWD/aws/secrets/ec2-pem-ssh.pem:/secrets/prod-key
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/contexts:/.docker/contexts
      - ./ancean-back:/ancean/ancean-back
      - ./ancean-front:/ancean/ancean-front
    ports:
      - 8080:8080
    networks:
      - ancean-local-net

secrets:
  django-connection:
    file: ./swarm/secrets/django-secrets.json

networks:
  ancean-local-net:
