env: stag
version: v1
namespace: ancean-stag

resourceQuota:
  cpu: 1000
  memory: 1Gi

api:
  rolloutSpead:
    minReadySeconds: 60
    progressDeadlineSeconds: 180
  # deploy:
  #   resources:
  #     memory: 400Mi
  #     cpu: 500m
  service:        
    servicePort: 6060
    targetPort: 8000
    serviceType: ClusterIP

web:
  rolloutSpead:
    minReadySeconds: 60
    progressDeadlineSeconds: 180
  # deploy:
  #   resources:
  #     memory: 200Mi
  #     cpu: 300m
  service:
    servicePort: 4040
    targetPort: 3000
    serviceType: ClusterIP

postgres:
  pv:
    storage: 2Gi
  service:
    servicePort: 5432
    targetPort: 5432
    serviceType: ClusterIP
    
nginx:
  service:
    servicePort: 80
    targetPort: 80
    serviceType: LoadBalancer

prometheus:
  namespace: ancean-stag-prometheus
  service:
    servicePort: 9090
    targetPort: 9090
    serviceType: LoadBalancer
  account:
    name: prometheus