# Default values for kube. --> dev env
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: stag
version: v1
namespace: ancean-stag

nfs:
  server: 192.168.1.10
  path: /srv/nfs4/ancean

resourceQuota:
  cpu: 1000
  memory: 1Gi

api:
  deploy:
    image: antoliny0919/ancean-back-stag:1.0.11
  rolloutSpead:
    minReadySeconds: 60
    progressDeadlineSeconds: 180
  service:        
    servicePort: 6060
    targetPort: 8000
    serviceType: ClusterIP

web:
  deploy:
    image: antoliny0919/ancean-front-stag:1.0.42
  rolloutSpead:
    minReadySeconds: 60
    progressDeadlineSeconds: 180
  service:
    servicePort: 4040
    targetPort: 3000
    serviceType: LoadBalancer

postgres:
  service:
    servicePort: 5432
    targetPort: 5432
    serviceType: ClusterIP
  exporter:
    port: 9187
    user: ancean
  pv:
    storage: 1Gi

nginx:
  service:
    serviceType: LoadBalancer
  exporter:
    port: 9113

redis:
  service:
    servicePort: 6379
    targetPort: 6379
    serviceType: LoadBalancer
    
prometheus:
  service:
    servicePort: 9090
    targetPort: 9090
    serviceType: LoadBalancer
  account:
    name: prometheus

grafana:
  theme: dark
  user: ancean
  password: ancean
  resources:
    cpu: 250m
    memory: 750Mi
  service:
    servicePort: 3000
    targetPort: 3000
    serviceType: LoadBalancer