version: "3.7"

services:
  api:
    image: antoliny0919/ancean-back-stag:latest
    deploy:
      replicas: 2
    secrets:
      - source: api-secrets
        target: /usr/app/ancean/secrets/django-secrets.json
    ports:
      - 6060:8000
    networks:
      - ancean-stag-net

  postgres:
    image: postgres:14
    deploy:
      replicas: 2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ancean
      POSTGRES_PASSWORD_FILE: /secrets/postgres-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - source: postgres-secrets
        target: /secrets/postgres-password
    networks:
      - ancean-stag-net

secrets:
  api-secrets:
    file: ./secrets/django-secrets.json
  postgres-secrets:
    file: ./secrets/postgres-password.txt

volumes:
  postgres_data:
    driver_opts:
      type: "nfs4"
      o: "addr=172.31.18.234,nolock,soft,rw"
      device: :/efs/postgres_data


networks:
  ancean-stag-net: