{{ $Name := .Release.Name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deploy
  namespace: {{ .Values.namespace }}
  labels: 
    ancean: {{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
      {{- with .Values.postgres.exporter }}
      annotations:
        prometheus.io/port: {{ .port | quote }}
      {{- end }}
    spec:
      containers:
        - name: {{ $Name }}-postgres-container
          image: postgres:15.3
          {{- if eq .Values.env "stag" }}
          readinessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-h", "localhost"]
            periodSeconds: 10
            initialDelaySeconds: 10
          {{- end }}
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "ancean"
            - name: POSTGRES_PASSWORD_FILE
              value: /secrets/postgres_password
          volumeMounts:
            - name: secret
              mountPath: "/secrets"
            # - name: nfs-volume
            #   mountPath: /backup
            #   subPath: postgres/backup/
        {{- with .Values.postgres.exporter }}
        - name: {{ $Name }}-postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.14.0
          ports:
            - name: metrics
              containerPort: {{ .port }}
          env:
            - name: DATA_SOURCE_URI
              value: localhost/postgres?sslmode=disable
            - name: DATA_SOURCE_USER
              value: {{ .user | quote }}
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: {{ $Name }}-postgres-secret
        {{- end }}
      volumes:
        - name: secret
          secret:
            secretName: {{ .Release.Name }}-postgres-secret
            defaultMode: 0400
            items:
              - key: POSTGRES_PASSWORD
                path: postgres_password
        # - name: nfs-volume
        #   nfs:
        #     server: {{ .Values.nfs.server }}
        #     path: {{ .Values.nfs.path }}