apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Values.namespace }}
  labels: 
    ancean: {{ .Values.env }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: "g=@#tlb074vn5av(3=(bp%lnmx1077y@oe2*pd3f729n4%5"