{{ $Name := .Release.Name }}
{{ $Env := .Values.env }}
{{ $Namespace := .Values.namespace }}
{{- with .Values.prometheus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $Name }}-prometheus-deploy
  namespace: {{ $Namespace }}-monitoring
spec:
  selector:
    matchLabels:
      app: {{ $Name }}-prometheus
  template:
    metadata:
      labels:
        app: {{ $Name }}-prometheus
    spec:
      serviceAccountName: {{ .account.name}}-account
  
      containers:
        - name: {{ $Name }}-prometheus-container
          image: prom/prometheus:v2.19.2
          args:
            - "--config.file=/config/prometheus.yml"
            - "--web.enable-lifecycle"
          ports:
            - containerPort: {{ .service.servicePort }}
          volumeMounts:
            - name: {{ $Name }}-prometheus-config
              mountPath: /config/
      volumes:
        - name: {{ $Name }}-prometheus-config
          configMap:
            name: {{ $Name }}-prometheus-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .account.name }}-account
  namespace: {{ $Namespace }}-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $Name}}-prometheus-CR
  labels:
    ancean: {{ $Env }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $Name }}-prometheus-CRB
  labels:
    ancean: {{ $Env }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $Name}}-prometheus-CR
subjects:
- kind: ServiceAccount
  name: {{ .account.name }}-account
  namespace: {{ $Namespace }}-monitoring
{{- end }}