{{ $Env := .Values.env }}
{{ $Namespace := .Values.namespace }}
{{- with .Values.prometheus }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $Namespace }}-monitoring
  labels:
    ancean: {{ $Env }}
{{- end }}