{{ $Name := .Release.Name }}
{{ $Env := .Values.env }}
{{- with .Values.prometheus }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $Name }}-prometheus-service
  namespace: {{ .namespace }}
  labels:
    ancean: {{ $Env }}
spec:
  selector: 
    app: {{ $Name }}-prometheus
  type: {{ .service.serviceType }} 
  ports:
    - port: {{ .service.servicePort }}
      targetPort: {{ .service.targetPort }}
{{- end }}