# Generated by Django 5.1 on 2024-08-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_writer',
            field=models.BooleanField(default=False, help_text='Specifies whether the user has permissions to work with the post.'),
        ),
    ]
