pipeline {
  agent any

  environment {
    IMAGE_TAG = 'v1.1.2'
    SCRIPT_PATH ='/var/jenkins_home/my_pipeline/deploy-back'
  }

  stages {
    stage('Build Stag') {
      steps {
        sh '''
        sh $SCRIPT_PATH/build.sh /ancean/ancean-back $IMAGE_TAG
        '''
      }
    }
    stage('Deploy Stag') {
      steps {
        sh '''
        sh $SCRIPT_PATH/deploy.sh $IMAGE_TAG
        '''
      }
    }
    stage('Test Stag') {
      steps {
        sh '''
        echo Test Stag"
        '''
      }
    }
    stage('Build Prod') {
      steps {
        sh '''
        echo Build Prod"
        '''
      }
    }
    stage('Deploy Prod') {
      steps {
        sh '''
        echo Deploy Prod"
        '''
      }
    }
  }
}