apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
  labels:
    ancean: {{ .Values.env }}
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - host: ancean.{{ .Values.env }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ancean-web-service
            port:
              number: {{ .Values.web.service.servicePort }}

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ancean-api-service
            port:
              number: {{ .Values.api.service.servicePort }}

      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: ancean-api-service
            port:
              number: {{ .Values.api.service.servicePort }}

      - path: /media
        pathType: Prefix
        backend:
          service:
            name: ancean-api-service
            port:
              number: {{ .Values.api.service.servicePort }}