apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-api-pvc
  namespace: {{ .Values.namespace }}
  labels: 
    ancean: {{ .Values.env }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""