apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-api-pv
  labels:
    ancean: {{ .Values.env }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /volumes/api
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: ancean
            operator: In
            values:
              - stag