apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
  namespace: {{ .Values.namespace }}
  labels:
    ancean: {{ .Values.env }}
type: Opaque
stringData:
  django-secrets.json: |-
    {
      "SECRET_KEY": "#*%(9@k3z#dr2y!(m35in!pxqq)luaa-0(_kgq3=lmsa+mo(#"
    }
  postgres-secrets.json: |-
    {
      "POSTGRES_PASSWORD": "g=@#tlb074vn5av(3=(bp%lnmx1077y@oe2*pd3f729n4%5",
      "POSTGRES_USER": "ancean",
      "POSTGRES_PORT": "5432",
      "POSTGRES_HOST": "{{ .Release.Name }}-postgres-service",
      "POSTGRES_DATABASE_NAME": "postgres"
    }
  oauth-secrets.json: |-
    {
      "GOOGLE": {
        "CLIENT_ID": "346589268566-me1msok46osgr6bs12eqph77tn2bh33l.apps.googleusercontent.com",
        "CLIENT_SECRET": "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"
      },
      "GITHUB": {
        "CLIENT_ID": "75128cffd7b6ba5f26b4",
        "CLIENT_SECRET": "88036ee5a2746ce58a8a4be97d7040295a2f8c67"
      },
      "KAKAO": {
        "CLIENT_ID": "22c13075453c19d0d6a1d8e303df37c2",
        "CLIENT_SECRET": "46Zp7Cgm4KtgGNgz74Jp7f5MxcZZnMGJ"
      }
    }