apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
  namespace: {{ .Values.namespace }}
  labels: 
    ancean: {{ .Values.env }}
spec:
  ports:
    - port: {{ .Values.api.service.servicePort }}
      targetPort: {{ .Values.api.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-api
  type: {{ .Values.api.service.serviceType }}