apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-deploy
  namespace: {{ .Values.namespace }}
  labels: 
    ancean: {{ .Values.env }}
spec: 
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  {{- with .Values.web.rolloutSpead }}
  minReadySeconds: {{ .minReadySeconds }}
  progressDeadlineSeconds: {{ .progressDeadlineSeconds }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
        version: {{ .Values.version }}
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: {{ .Release.Name }}-web-container
          image: antoliny0919/ancean-front-stag:1.0.2