apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  namespace: {{ .Values.namespace }}
  labels: 
    ancean: {{ .Values.env }}
spec:
  ports:
    - port: {{ .Values.web.service.servicePort }}
      targetPort: {{ .Values.web.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-web
  type: {{ .Values.web.service.serviceType }}