pipeline {
  agent any

  environment {
    IMAGE_TAG = 'v1.1.2'
    SCRIPT_PATH ='/var/jenkins_home/my_pipeline/deploy-back-stag'
  }

  stages {
    stage('Build') {
      steps {
        sh '''
        sh $SCRIPT_PATH/build.sh /ancean/ancean-back $IMAGE_TAG
        '''
      }
    }
    stage('Deploy') {
      steps {
        sh '''
        sh $SCRIPT_PATH/deploy.sh $IMAGE_TAG
        '''
      }
    }
    stage('Test Stag') {
      steps {
        sh '''
        echo Test Stag
        '''
      }
    }
  }
}