{{ $Name := .Release.Name }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-nginx-daemonset
  namespace: {{ .Values.namespace }}
  labels: 
    ancean: {{ .Values.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  {{- with .rolloutSpead }}
  minReadySeconds: {{ .minReadySeconds }}
  progressDeadlineSeconds: {{ .progressDeadlineSeconds }}
  {{- end }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
        version: {{ .Values.version }}
      {{- with .Values.nginx.exporter }}
      annotations:
        prometheus.io/port: {{ .port | quote }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Release.Name }}-nginx-container
          image: nginx:1.24.0
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/
              readOnly: true
            - name: cert
              mountPath: /etc/cert/
            - name: nfs-volume
              mountPath: /app/usr
              subPath: api/
            - name: cache-volume
              mountPath: /data/nginx/cache
        {{- with .Values.nginx.exporter }}
        - name: {{ $Name }}-nginx-exporter
          image: nginx/nginx-prometheus-exporter:1.0.0
          ports:
            - name: metrics
              containerPort: {{ .port }}
          args:
            - -nginx.scrape-uri=http://localhost/stub_status
        {{ end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-nginx-config
        - name: cert
          secret:
            secretName: {{ .Release.Name }}-nginx-secret
        - name: nfs-volume
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
        - name: cache-volume
          hostPath:
            path: /volumes/nginx-cache
            type: DirectoryOrCreate