{{ $Env := .Values.env }}
{{ $Ver := .Values.version }}
{{ $Name := .Release.Name }}
{{ $Namespace := .Values.namespace }}
{{- with .Values.nginx }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $Name }}-nginx-daemonset
  namespace: {{ $Namespace }}
  labels: 
    ancean: {{ $Env }}
spec:
  selector:
    matchLabels:
      app: {{ $Name }}-nginx
  # {{- with .rolloutSpead }}
  # minReadySeconds: {{ .minReadySeconds }}
  # progressDeadlineSeconds: {{ .progressDeadlineSeconds }}
  # {{- end }}
  # {{- if eq $Env "stag" }}
  # updateStrategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 0
  # {{- end }}
  template:
    metadata:
      labels:
        app: {{ $Name }}-nginx
        version: {{ $Ver }}
      # {{- with .exporter }}
      # annotations:
      #   prometheus.io/port: {{ .port | quote }}
      # {{- end }}
    spec:
      containers:
        - name: {{ $Name }}-nginx-container
          image: nginx:1.24.0
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/
              readOnly: true
            - name: cert
              mountPath: /etc/cert/
            # - name: media-static
            #   mountPath: /app/usr/
        # {{- with .exporter }}
        # - name: {{ $Env }}-nginx-exporter
        #   image: nginx/nginx-prometheus-exporter:1.0.0
        #   ports:
        #     - name: metrics
        #       containerPort: {{ .port }}
        #   args:
        #     - -nginx.scrape-uri=http://localhost/stub_status
        # {{ end }}
      volumes:
        - name: config
          configMap:
            name: {{ $Name }}-nginx-config
        # - name: cache-volume
        #   hostPath:
        #     path: /volumes/nginx-cache
        #     type: DirectoryOrCreate
        - name: cert
          secret:
            secretName: {{ $Name }}-nginx-secret
{{- end }}