apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nginx-secret
  namespace: {{ .Values.namespace }}
  labels:
    ancean: {{ .Values.env }}
type: Opaque
stringData:
  SSL_KEY_PEM: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC1qeV/VIX1dm7A
    A65pfVlgcem6+hYBpJaNhvEMwjvKa0+PCrb7BVId9DoUOagf8Ze5PbDZCaQ6Jhdz
    v4n4wmig4F+075dOXJl7+hlzDas0z5FtTuxhuy1tijw/+U2SSWYK1Ze0PcWo3gu+
    YiZsIy4Wex6z3DOOQJhsiwNnVfWAo0Kxq5rI7RWVq0c27sHuyMFe2WrVPOQ2qwoh
    J5+zAX1YVP6aWSM1AzRc3V3VW+0tVRWClI4y50gK8X9uRevaEJREcHefVlMuKA2v
    NJ1GXfG0cyVKxdV714NEvOBkUF+uqTkVh7OBmUGU79ysIco+q4zt7J3vnB8Tmy8b
    VnapnGDdAgMBAAECggEBAJnxDvmHtrz7T36HoBTklAiWf2pi4qMhxjLIVxxovCIc
    LZ8ZhVXSfHPFsjHRahcns1rWXDaPZQuhm94KQfD7TY6GlJPPNHjDH41fspE81Ag8
    nQ/0AXwQEb7xlXzg1ktQx5gGyDeE4SrofysmIUkhxrxmOO5Re57gPko8wvWechw+
    zu89JAjFTyBK5bHPhHVNst/rT131zoCEJzE0NVoaxvcBvgMyy9XONNYuilqcRxVL
    7BNVBiz47fySzmfbinuy6R3G9H017ikTXCCRnyZqWIQZ95p7/8VYx1Pb2YxvfLAF
    fqckg9GN36oeyj37nj2SgzMKilxA2owrW/XFbfoABkECgYEA5Pqk7aoNP9yfINl/
    93A2wuTnptdXp3Oasm8shYxzLNaGp041fKV2KSkDOl2478rotjVx5WG5Bi9Q71Gm
    CSyXR+1avciToJsmG1mgPVN9tFOQDanHoaKG6XD+v0oMtyFM66r3koznq98+VxYF
    kSk7hgZYOq09I/isn1n96Ct4HycCgYEAyxnf3dg/rbjtcMxCzgMrgxjRnLZBqtj0
    3tyO3/dtMatv1suVFrNsP3lQEZOh8w05QSOuO1tmVWCaGIHqqUOAWzw8890z7mSu
    4Cw2yEYG0WjqMUZVL1f8GBwBxg1Q0XznQs+qQsfqz/BC3urTl73QflxE0bYc8JJ1
    tw+XrDfdAlsCgYBsaXNvByVwyA8baX8Z8yoqSmCXcLuSj7x9oP9uV5osb4GfcvsG
    Af0Y7c8WckteVS6rHlDHruYAVKS4OmsnStJxfqKI2o9y6iI3rs6cWoxYtXutzGW1
    VJMVsacbgH7WsdCOgArpewcxK+iDKO0H1oLVKOnbFiytfE6Wv+/kXbho3wKBgBiP
    T2/vN3wVcbkDKkzpOzjGJorRy00SoUHV3/0bWXv5JDQQOD4fgkaGr/UAKkRO5A6J
    dwc8fTpzzQ6Ln0nKnNnrhd9jb2UzjaYUEqfTN/3YtwEwZRqthBGSSXCeqZg7h2ef
    3xHmRPHSNvPn56Bg1raBB91oLUW2ID/7xbaQpswjAoGBAJziRosalZ9g/BcVHYBy
    lUDafLLtCWAmmuVTlxsFTpZtq/oLGAVvG43yDivGykSgeCeme4AV7oMLIXWV3EwO
    9gNiMATWBfAbE7oYRk4AGWMUGi95RvRc0dO97AK7g8H8vozhjkJrnWQYGQS478wT
    SHRlgsLf+QcKt8HmeU+DGoPX
    -----END PRIVATE KEY-----
  SSL_PEM: |
    -----BEGIN CERTIFICATE-----
    MIIEkTCCAvmgAwIBAgIQWUEUudZYrffPExR8ETDDkzANBgkqhkiG9w0BAQsFADCB
    nTEeMBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMTkwNwYDVQQLDDBhbnRv
    bGlueUBpc2loeWVvbnMtTWFjQm9vay1BaXIubG9jYWwgKOydtOyLnO2YhCkxQDA+
    BgNVBAMMN21rY2VydCBhbnRvbGlueUBpc2loeWVvbnMtTWFjQm9vay1BaXIubG9j
    YWwgKOydtOyLnO2YhCkwHhcNMjQwNDA2MTM1MjMxWhcNMjYwNzA2MTM1MjMxWjBk
    MScwJQYDVQQKEx5ta2NlcnQgZGV2ZWxvcG1lbnQgY2VydGlmaWNhdGUxOTA3BgNV
    BAsMMGFudG9saW55QGlzaWh5ZW9ucy1NYWNCb29rLUFpci5sb2NhbCAo7J207Iuc
    7ZiEKTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALWp5X9UhfV2bsAD
    rml9WWBx6br6FgGklo2G8QzCO8prT48KtvsFUh30OhQ5qB/xl7k9sNkJpDomF3O/
    ifjCaKDgX7Tvl05cmXv6GXMNqzTPkW1O7GG7LW2KPD/5TZJJZgrVl7Q9xajeC75i
    JmwjLhZ7HrPcM45AmGyLA2dV9YCjQrGrmsjtFZWrRzbuwe7IwV7ZatU85DarCiEn
    n7MBfVhU/ppZIzUDNFzdXdVb7S1VFYKUjjLnSArxf25F69oQlERwd59WUy4oDa80
    nUZd8bRzJUrF1XvXg0S84GRQX66pORWHs4GZQZTv3Kwhyj6rjO3sne+cHxObLxtW
    dqmcYN0CAwEAAaOBhDCBgTAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYB
    BQUHAwEwHwYDVR0jBBgwFoAUq8VVODVsa4DJAEpqkmtQWWZufOMwOQYDVR0RBDIw
    MIILYW5jZWFuLnN0YWeCCWxvY2FsaG9zdIcEfwAAAYcQAAAAAAAAAAAAAAAAAAAA
    ATANBgkqhkiG9w0BAQsFAAOCAYEAgaWA/3E5MRz3m/zS0LfRds5PK/rX4M52FEQE
    IGvDH9coSEE10RxSVeiWXViHhhVo5uVzoJsAQFPQZFG+OqqIiP0unIENs0u0BuKX
    9lT7nNvM1RP5neFyLh/0CAWih0f8icG4dOr1RU1fmbjjqicxOYTve/7cJU/ASlj7
    Vr0+ojtcjMfq9SCNRY9OLXf2vW+V0kPOCUfBkuy3PoUJ2tucorKaZbMo5GxZvaG9
    igIiBNPDSB5BbGRSKyu86v9mY1ASArfnwywPU+XF62l++FXDv1+O9FCg9AXBgn59
    66X842iUBo7sXBPbJ/i8ZiuBFBQThUZOgk4sAROtj6jId7YpKUDHVm+TaixEyB2k
    kMQZpL7qVWNZYJ/tGl+9Qc26ki4zxjaPiFIq/q+ZjyZik3wzOMxpQktUpEAnKN59
    CgndqIZjrDVWfcDTZIEpB4SQnj+mj+j+nf4G8Sqh4zaD4EB0fOnj0rZfA28uFMdt
    ZcUqbM+2RGaQ8Srm30jczZNM0qa1
    -----END CERTIFICATE-----