apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nginx-secret
  namespace: {{ .Values.namespace }}
  labels:
    ancean: {{ .Values.env }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "x509/nginx-tls.crt" | b64enc }}

  tls.key: {{ .Files.Get "x509/nginx-tls.key" | b64enc }}