{{ $Name := .Release.Name }}
{{ $Namespace := .Values.namespace }}
{{ $Env := .Values.env }}
{{- with .Values.nginx }}
apiVersion: v1
kind: Service
metadata: 
  name: {{ $Name }}-nginx-service
  namespace: {{ $Namespace }}
  labels: 
    ancean: {{ $Env }}
spec:
  ports:
    - port: {{ .service.servicePort }}
      targetPort: {{ .service.targetPort }}
  selector:
    app: {{ $Name }}-nginx
  type: {{ .service.serviceType }}
{{- end }}