{
 "title": "Ancean-pods",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"postgres\", state=\"active\"}",
     "legendFormat": "activity"
    }
   ]
  },
  {
   "title": "Idle Sessions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"postgres\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Data Queried",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{datname=\"postgres\"}[5m]))",
     "legendFormat": "reads"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=\"postgres\"}[5m]))",
     "legendFormat": "writes"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"postgres\"}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request(5M)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{app=\"ancean-nginx\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections(5M)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted{app=\"ancean-nginx\"}[5m]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(nginx_connections_handled{app=\"ancean-nginx\"}[5m]))",
     "legendFormat": "handled"
    }
   ]
  },
  {
   "title": "Active Connection",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_connections_active{app=\"ancean-nginx\"}",
     "legendFormat": "active"
    },
    {
     "expr": "nginx_connections_reading{app=\"ancean-nginx\"}",
     "legendFormat": "reading"
    },
    {
     "expr": "nginx_connections_waiting{app=\"ancean-nginx\"}",
     "legendFormat": "waiting"
    },
    {
     "expr": "nginx_connections_writing{app=\"ancean-nginx\"}",
     "legendFormat": "writing"
    }
   ]
  }
 ]
}